-- AstraCorp - territorios multijugador online
-- Version compatible con Supabase SQL Editor.

create table if not exists public.game_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.game_saves enable row level security;

drop policy if exists "Players can read own save" on public.game_saves;
create policy "Players can read own save"
  on public.game_saves for select
  using (auth.uid() = user_id);

drop policy if exists "Players can write own save" on public.game_saves;
create policy "Players can write own save"
  on public.game_saves for insert
  with check (auth.uid() = user_id);

drop policy if exists "Players can update own save" on public.game_saves;
create policy "Players can update own save"
  on public.game_saves for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.astracorp_global_territories (
  territory_id integer primary key,
  state jsonb not null,
  controller text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.astracorp_global_territories enable row level security;

drop policy if exists "Players can read global territories" on public.astracorp_global_territories;
create policy "Players can read global territories"
  on public.astracorp_global_territories for select
  to authenticated
  using (true);

create table if not exists public.astracorp_territory_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  territory_id integer not null,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists astracorp_territory_events_user_action_idx
  on public.astracorp_territory_events(user_id, action, territory_id, created_at desc);

alter table public.astracorp_territory_events enable row level security;

drop policy if exists "Players can read own territory events" on public.astracorp_territory_events;
create policy "Players can read own territory events"
  on public.astracorp_territory_events for select
  using (auth.uid() = user_id);

create or replace function public._astracorp_clamp(p_value numeric, p_min numeric, p_max numeric)
returns numeric
as $fn$
  select least(p_max, greatest(p_min, coalesce(p_value, p_min)));
$fn$
language sql
immutable;

create or replace function public._astracorp_check_cooldown(p_action text, p_territory_id integer, p_seconds integer)
returns void
as $fn$
declare
  v_user uuid := auth.uid();
  v_last timestamptz;
  v_remaining integer;
begin
  if v_user is null then
    raise exception 'Debes iniciar sesion.';
  end if;

  select created_at into v_last
  from public.astracorp_territory_events
  where user_id = v_user
    and action = p_action
    and territory_id = p_territory_id
  order by created_at desc
  limit 1;

  if v_last is not null and v_last > now() - make_interval(secs => p_seconds) then
    v_remaining := greatest(1, ceil(extract(epoch from (v_last + make_interval(secs => p_seconds) - now())))::int);
    raise exception 'Accion en enfriamiento. Espera % segundos.', v_remaining;
  end if;
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_seed_global_territories(p_user uuid, p_save jsonb)
returns void
as $fn$
begin
  insert into public.astracorp_global_territories(territory_id, state, controller, updated_by, updated_at)
  select (territory->>'id')::int, territory, nullif(territory->>'controller', ''), p_user, now()
  from jsonb_array_elements(coalesce(p_save->'territories', '[]'::jsonb)) territory
  where territory ? 'id'
  on conflict (territory_id) do nothing;
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_apply_global_territories(p_save jsonb)
returns jsonb
as $fn$
declare
  v_territories jsonb;
begin
  select jsonb_agg(coalesce(global_state.state, local_state.territory) order by local_state.ord)
  into v_territories
  from jsonb_array_elements(coalesce(p_save->'territories', '[]'::jsonb)) with ordinality local_state(territory, ord)
  left join public.astracorp_global_territories global_state
    on global_state.territory_id = (local_state.territory->>'id')::int;

  if v_territories is null then
    return p_save;
  end if;

  return jsonb_set(p_save, '{territories}', v_territories, true);
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_load_save_locked()
returns jsonb
as $fn$
declare
  v_user uuid := auth.uid();
  v_save jsonb;
begin
  if v_user is null then
    raise exception 'Debes iniciar sesion.';
  end if;

  select save_data into v_save
  from public.game_saves
  where user_id = v_user
  for update;

  if v_save is null then
    raise exception 'No hay partida guardada en esta cuenta.';
  end if;

  perform public._astracorp_seed_global_territories(v_user, v_save);
  return public._astracorp_apply_global_territories(v_save);
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_store_save(p_save jsonb)
returns void
as $fn$
begin
  update public.game_saves
  set save_data = p_save,
      updated_at = now()
  where user_id = auth.uid();
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_write_global_territory(p_territory_id integer, p_state jsonb)
returns void
as $fn$
begin
  insert into public.astracorp_global_territories(territory_id, state, controller, updated_by, updated_at)
  values (p_territory_id, p_state, nullif(p_state->>'controller', ''), auth.uid(), now())
  on conflict (territory_id) do update set
    state = excluded.state,
    controller = excluded.controller,
    updated_by = excluded.updated_by,
    updated_at = now();
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_set_player_values(p_save jsonb, p_credits numeric, p_energy numeric, p_health numeric default null)
returns jsonb
as $fn$
declare
  v_player jsonb := coalesce(p_save->'player', '{}'::jsonb);
begin
  v_player := jsonb_set(v_player, '{credits}', to_jsonb(round(greatest(0, p_credits)::numeric, 2)), true);
  v_player := jsonb_set(v_player, '{energy}', to_jsonb(greatest(0, floor(p_energy))::int), true);

  if p_health is not null then
    v_player := jsonb_set(v_player, '{health}', to_jsonb(public._astracorp_clamp(p_health, 0, 100)), true);
  end if;

  return jsonb_set(p_save, '{player}', v_player, true);
end;
$fn$
language plpgsql
immutable;

create or replace function public.rpc_get_global_territories()
returns jsonb
as $fn$
declare
  v_save jsonb;
begin
  v_save := public._astracorp_load_save_locked();
  perform public._astracorp_store_save(v_save);

  return jsonb_build_object(
    'ok', true,
    'territories', coalesce(v_save->'territories', '[]'::jsonb),
    'saveData', v_save
  );
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_attack_territory_secure(p_territory_id integer)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_territory jsonb;
  v_new_territory jsonb;
  v_territories jsonb;
  v_campaign jsonb;
  v_next_campaign jsonb;
  v_memory jsonb;
  v_player_name text;
  v_credits numeric;
  v_energy numeric;
  v_health numeric;
  v_level numeric;
  v_inventory jsonb;
  v_controlled numeric;
  v_attack_power numeric;
  v_defense_power numeric;
  v_current_progress numeric;
  v_progress_gain numeric;
  v_next_progress numeric;
  v_chance numeric;
  v_win boolean;
  v_completed boolean := false;
  v_reward numeric := 0;
  v_stats jsonb;
begin
  perform public._astracorp_check_cooldown('attack', p_territory_id, 45);

  v_save := public._astracorp_load_save_locked();
  v_player_name := coalesce(v_save #>> '{player,name}', 'Jugador');
  v_credits := coalesce((v_save #>> '{player,credits}')::numeric, 0);
  v_energy := coalesce((v_save #>> '{player,energy}')::numeric, 0);
  v_health := coalesce((v_save #>> '{player,health}')::numeric, 100);
  v_level := coalesce((v_save #>> '{player,level}')::numeric, 1);
  v_inventory := coalesce(v_save->'inventory', '{}'::jsonb);

  select territory into v_territory
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) territory
  where (territory->>'id')::int = p_territory_id
  limit 1;

  if v_territory is null then raise exception 'Territorio no valido.'; end if;
  if v_territory->>'controller' = v_player_name then raise exception 'Ya controlas este territorio.'; end if;
  if v_energy < 32 then raise exception 'Necesitas 32 de energia.'; end if;
  if v_credits < 4 then raise exception 'Necesitas 4 creditos.'; end if;
  if v_health < 15 then raise exception 'Integridad critica: repara en la sede antes de conquistar.'; end if;

  select count(*) into v_controlled
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) territory
  where territory->>'controller' = v_player_name;

  v_campaign := case
    when v_territory ? 'campaign' and coalesce(v_territory->'campaign'->>'ownerName', '') = v_player_name
      then v_territory->'campaign'
    else null
  end;
  v_current_progress := public._astracorp_clamp(coalesce((v_campaign->>'progress')::numeric, 0), 0, 100);
  v_attack_power :=
    8
    + v_level * 2.1
    + v_controlled * 0.7
    + sqrt(greatest(0, coalesce((v_inventory->>'mineral')::numeric, 0)));
  v_defense_power := greatest(
    8,
    case when coalesce(v_territory->>'controller', '') <> '' then 24 else 15 end
      + coalesce((v_territory->>'stability')::numeric, 0) * 0.26
      + coalesce((v_territory->>'fortification')::numeric, 0) * 0.34
      - coalesce((v_territory->>'threat')::numeric, 0) * 0.05
  );
  v_chance := public._astracorp_clamp(
    42 + (v_attack_power - v_defense_power) * 3.4 + v_current_progress * 0.1,
    case when coalesce(v_territory->>'controller', '') <> '' then 8 else 16 end,
    case when coalesce(v_territory->>'controller', '') <> '' then 62 else 76 end
  );
  v_win := random() * 100 < v_chance;
  v_progress_gain := case
    when v_win and coalesce(v_territory->>'controller', '') <> '' then 26
    when v_win then 38
    when coalesce(v_territory->>'controller', '') <> '' then 6
    else 10
  end;
  v_next_progress := public._astracorp_clamp(v_current_progress + v_progress_gain, 0, 100);
  v_completed := v_win and v_next_progress >= 100;

  if v_completed then
    v_reward := round((greatest(4, v_defense_power / 4.2 + coalesce((v_territory->>'threat')::numeric, 0) * 0.06) * (0.9 + random() * 0.3))::numeric, 2);
    v_memory := coalesce(v_territory->'sectorMemory', '{}'::jsonb)
      || jsonb_build_object(
        'firstControlledAt', coalesce(v_territory #> '{sectorMemory,firstControlledAt}', to_jsonb(floor(extract(epoch from clock_timestamp()) * 1000)::numeric)),
        'firstControlledDay', coalesce(v_territory #> '{sectorMemory,firstControlledDay}', to_jsonb(coalesce((v_save->>'day')::int, 1))),
        'lastConqueredAt', floor(extract(epoch from clock_timestamp()) * 1000)::numeric,
        'lastConqueredDay', coalesce((v_save->>'day')::int, 1),
        'conqueredCount', coalesce((v_territory #>> '{sectorMemory,conqueredCount}')::int, 0) + 1,
        'lastEvent', 'Conquistado por ' || v_player_name
      );
    v_new_territory := jsonb_set(v_territory, '{controller}', to_jsonb(v_player_name), true);
    v_new_territory := jsonb_set(v_new_territory, '{stability}', to_jsonb(58), true);
    v_new_territory := jsonb_set(v_new_territory, '{threat}', to_jsonb(38), true);
    v_new_territory := jsonb_set(v_new_territory, '{fortification}', to_jsonb(greatest(6, coalesce((v_territory->>'fortification')::numeric, 0))), true);
    v_new_territory := jsonb_set(v_new_territory, '{campaign}', 'null'::jsonb, true);
    v_new_territory := jsonb_set(v_new_territory, '{enemyCampaign}', 'null'::jsonb, true);
    v_new_territory := jsonb_set(v_new_territory, '{siegeTick}', to_jsonb(0), true);
    v_new_territory := jsonb_set(v_new_territory, '{siegeAttacker}', 'null'::jsonb, true);
    v_new_territory := jsonb_set(v_new_territory, '{siegeStartedAt}', 'null'::jsonb, true);
    v_new_territory := jsonb_set(v_new_territory, '{sectorMemory}', v_memory, true);
  else
    v_next_campaign := jsonb_build_object(
      'ownerName', v_player_name,
      'progress', v_next_progress,
      'stageId', case
        when v_next_progress >= 76 then 'consolidation'
        when v_next_progress >= 51 then 'assault'
        when v_next_progress >= 26 then 'sabotage'
        else 'recon'
      end,
      'attempts', coalesce((v_campaign->>'attempts')::int, 0) + 1,
      'targetController', nullif(v_territory->>'controller', ''),
      'updatedAt', floor(extract(epoch from clock_timestamp()) * 1000)::numeric
    );
    v_new_territory := jsonb_set(v_territory, '{campaign}', v_next_campaign, true);
    v_new_territory := jsonb_set(
      v_new_territory,
      '{stability}',
      to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'stability')::numeric, 0) - case when v_win then 4 else 1 end, 0, 100)),
      true
    );
    v_new_territory := jsonb_set(
      v_new_territory,
      '{threat}',
      to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'threat')::numeric, 0) + case when v_win then 5 else 2 end, 0, 100)),
      true
    );
  end if;

  select jsonb_agg(case when (territory->>'id')::int = p_territory_id then v_new_territory else territory end order by ord)
  into v_territories
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) with ordinality items(territory, ord);

  v_save := jsonb_set(v_save, '{territories}', v_territories, true);
  v_save := public._astracorp_set_player_values(v_save, v_credits - 4 + v_reward, v_energy - 32, case when v_win then v_health - 7 else v_health - 24 end);

  v_stats := coalesce(v_save->'stats', '{}'::jsonb);
  v_stats := jsonb_set(v_stats, '{battles}', to_jsonb(coalesce((v_stats->>'battles')::int, 0) + 1), true);
  v_stats := jsonb_set(v_stats, '{conquests}', to_jsonb(coalesce((v_stats->>'conquests')::int, 0) + case when v_completed then 1 else 0 end), true);
  v_save := jsonb_set(v_save, '{stats}', v_stats, true);

  perform public._astracorp_write_global_territory(p_territory_id, v_new_territory);

  insert into public.astracorp_territory_events(user_id, territory_id, action, payload)
  values (auth.uid(), p_territory_id, 'attack', jsonb_build_object(
    'win', v_win,
    'completed', v_completed,
    'rewardCredits', v_reward,
    'chance', v_chance,
    'progress', v_next_progress
  ));

  perform public._astracorp_store_save(v_save);

  return jsonb_build_object(
    'ok', true,
    'saveData', v_save,
    'result', jsonb_build_object(
      'win', v_win,
      'completed', v_completed,
      'rewardCredits', v_reward,
      'chance', v_chance,
      'progress', v_next_progress
    )
  );
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_reinforce_territory_secure(p_territory_id integer)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_territory jsonb;
  v_new_territory jsonb;
  v_territories jsonb;
  v_player_name text;
  v_credits numeric;
  v_energy numeric;
begin
  perform public._astracorp_check_cooldown('reinforce', p_territory_id, 60);

  v_save := public._astracorp_load_save_locked();
  v_player_name := coalesce(v_save #>> '{player,name}', 'Jugador');
  v_credits := coalesce((v_save #>> '{player,credits}')::numeric, 0);
  v_energy := coalesce((v_save #>> '{player,energy}')::numeric, 0);

  select territory into v_territory
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) territory
  where (territory->>'id')::int = p_territory_id
  limit 1;

  if v_territory is null then raise exception 'Territorio no valido.'; end if;
  if v_territory->>'controller' <> v_player_name then raise exception 'Solo puedes reforzar territorios bajo tu control.'; end if;
  if v_credits < 10 then raise exception 'Necesitas 10 creditos.'; end if;
  if v_energy < 6 then raise exception 'Necesitas 6 de energia.'; end if;

  v_new_territory := jsonb_set(v_territory, '{stability}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'stability')::numeric, 0) + 28, 0, 100)), true);
  v_new_territory := jsonb_set(v_new_territory, '{threat}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'threat')::numeric, 0) - 34, 0, 100)), true);
  v_new_territory := jsonb_set(v_new_territory, '{fortification}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'fortification')::numeric, 0) + 26, 0, 100)), true);

  select jsonb_agg(case when (territory->>'id')::int = p_territory_id then v_new_territory else territory end order by ord)
  into v_territories
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) with ordinality items(territory, ord);

  v_save := jsonb_set(v_save, '{territories}', v_territories, true);
  v_save := public._astracorp_set_player_values(v_save, v_credits - 10, v_energy - 6);

  perform public._astracorp_write_global_territory(p_territory_id, v_new_territory);

  insert into public.astracorp_territory_events(user_id, territory_id, action)
  values (auth.uid(), p_territory_id, 'reinforce');

  perform public._astracorp_store_save(v_save);
  return jsonb_build_object('ok', true, 'saveData', v_save, 'message', 'Refuerzo desplegado online.');
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_sabotage_territory_secure(p_territory_id integer)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_territory jsonb;
  v_new_territory jsonb;
  v_territories jsonb;
  v_player_name text;
  v_credits numeric;
  v_energy numeric;
begin
  perform public._astracorp_check_cooldown('sabotage', p_territory_id, 90);

  v_save := public._astracorp_load_save_locked();
  v_player_name := coalesce(v_save #>> '{player,name}', 'Jugador');
  v_credits := coalesce((v_save #>> '{player,credits}')::numeric, 0);
  v_energy := coalesce((v_save #>> '{player,energy}')::numeric, 0);

  select territory into v_territory
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) territory
  where (territory->>'id')::int = p_territory_id
  limit 1;

  if v_territory is null then raise exception 'Territorio no valido.'; end if;
  if coalesce(v_territory->>'controller', '') = '' or v_territory->>'controller' = v_player_name then raise exception 'Solo puedes sabotear territorios hostiles.'; end if;
  if v_credits < 8 then raise exception 'Necesitas 8 creditos para sabotear.'; end if;
  if v_energy < 5 then raise exception 'Necesitas 5 de energia.'; end if;

  v_new_territory := jsonb_set(v_territory, '{stability}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'stability')::numeric, 0) - 10, 0, 100)), true);
  v_new_territory := jsonb_set(v_new_territory, '{threat}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'threat')::numeric, 0) + 14, 0, 100)), true);
  v_new_territory := jsonb_set(v_new_territory, '{fortification}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'fortification')::numeric, 0) - 8, 0, 100)), true);

  select jsonb_agg(case when (territory->>'id')::int = p_territory_id then v_new_territory else territory end order by ord)
  into v_territories
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) with ordinality items(territory, ord);

  v_save := jsonb_set(v_save, '{territories}', v_territories, true);
  v_save := public._astracorp_set_player_values(v_save, v_credits - 8, v_energy - 5);

  perform public._astracorp_write_global_territory(p_territory_id, v_new_territory);

  insert into public.astracorp_territory_events(user_id, territory_id, action)
  values (auth.uid(), p_territory_id, 'sabotage');

  perform public._astracorp_store_save(v_save);
  return jsonb_build_object('ok', true, 'saveData', v_save, 'message', 'Sabotaje completado online.');
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_build_territory_fort_secure(p_territory_id integer)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_territory jsonb;
  v_new_territory jsonb;
  v_territories jsonb;
  v_inventory jsonb;
  v_player_name text;
  v_fort numeric;
  v_tier int;
  v_mineral numeric;
  v_metal numeric;
  v_alloy numeric;
begin
  perform public._astracorp_check_cooldown('build_fort', p_territory_id, 120);

  v_save := public._astracorp_load_save_locked();
  v_player_name := coalesce(v_save #>> '{player,name}', 'Jugador');
  v_inventory := coalesce(v_save->'inventory', '{}'::jsonb);

  select territory into v_territory
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) territory
  where (territory->>'id')::int = p_territory_id
  limit 1;

  if v_territory is null then raise exception 'Territorio no valido.'; end if;
  if v_territory->>'controller' <> v_player_name then raise exception 'Solo puedes construir fortines en territorios bajo tu control.'; end if;

  v_fort := coalesce((v_territory->>'fortification')::numeric, 0);
  if v_fort >= 100 then raise exception 'Este territorio ya esta completamente fortificado.'; end if;

  v_tier := floor(v_fort / 25);
  v_mineral := 8 + v_tier * 4;
  v_metal := 3 + v_tier * 2;
  v_alloy := case when v_fort >= 50 then 1 + floor((v_fort - 50) / 25) else 0 end;

  if coalesce((v_inventory->>'mineral')::numeric, 0) < v_mineral
    or coalesce((v_inventory->>'metal_components')::numeric, 0) < v_metal
    or coalesce((v_inventory->>'alloy_frames')::numeric, 0) < v_alloy then
    raise exception 'Faltan recursos para el fortin.';
  end if;

  v_inventory := jsonb_set(v_inventory, '{mineral}', to_jsonb(coalesce((v_inventory->>'mineral')::numeric, 0) - v_mineral), true);
  v_inventory := jsonb_set(v_inventory, '{metal_components}', to_jsonb(coalesce((v_inventory->>'metal_components')::numeric, 0) - v_metal), true);
  v_inventory := jsonb_set(v_inventory, '{alloy_frames}', to_jsonb(coalesce((v_inventory->>'alloy_frames')::numeric, 0) - v_alloy), true);

  v_new_territory := jsonb_set(v_territory, '{fortification}', to_jsonb(public._astracorp_clamp(v_fort + 22, 0, 100)), true);
  v_new_territory := jsonb_set(v_new_territory, '{stability}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'stability')::numeric, 0) + 10, 0, 100)), true);
  v_new_territory := jsonb_set(v_new_territory, '{threat}', to_jsonb(public._astracorp_clamp(coalesce((v_territory->>'threat')::numeric, 0) - 18, 0, 100)), true);
  v_new_territory := jsonb_set(v_new_territory, '{fortLevel}', to_jsonb(coalesce((v_territory->>'fortLevel')::int, 0) + 1), true);

  select jsonb_agg(case when (territory->>'id')::int = p_territory_id then v_new_territory else territory end order by ord)
  into v_territories
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) with ordinality items(territory, ord);

  v_save := jsonb_set(v_save, '{territories}', v_territories, true);
  v_save := jsonb_set(v_save, '{inventory}', v_inventory, true);

  perform public._astracorp_write_global_territory(p_territory_id, v_new_territory);

  insert into public.astracorp_territory_events(user_id, territory_id, action)
  values (auth.uid(), p_territory_id, 'build_fort');

  perform public._astracorp_store_save(v_save);
  return jsonb_build_object('ok', true, 'saveData', v_save, 'message', 'Fortin construido online.');
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_collect_occupation_taxes_secure(p_territory_id integer)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_player_name text;
  v_territory jsonb;
  v_company jsonb;
  v_companies jsonb := '[]'::jsonb;
  v_inventory jsonb;
  v_resource text;
  v_pending numeric;
  v_collected jsonb := '{}'::jsonb;
  v_collected_text text := '';
begin
  perform public._astracorp_check_cooldown('collect_tax', p_territory_id, 30);

  v_save := public._astracorp_load_save_locked();
  v_player_name := coalesce(v_save #>> '{player,name}', 'Jugador');
  v_inventory := coalesce(v_save->'inventory', '{}'::jsonb);

  select territory into v_territory
  from jsonb_array_elements(coalesce(v_save->'territories', '[]'::jsonb)) territory
  where (territory->>'id')::int = p_territory_id
  limit 1;

  if v_territory is null or v_territory->>'controller' <> v_player_name then
    raise exception 'Solo puedes cobrar tasas de territorios bajo tu control.';
  end if;

  for v_company in select value from jsonb_array_elements(coalesce(v_save->'companies', '[]'::jsonb)) loop
    v_pending := coalesce((v_company->>'occupationTaxPending')::numeric, 0);

    if coalesce((v_company->>'territoryId')::int, -1) = p_territory_id
      and coalesce(v_company->>'occupiedBy', '') = v_player_name
      and v_pending > 0 then
      v_resource := coalesce(nullif(v_company->>'occupationTaxResourceKey', ''), 'mineral');
      v_inventory := jsonb_set(v_inventory, array[v_resource], to_jsonb(coalesce((v_inventory->>v_resource)::numeric, 0) + v_pending), true);
      v_collected := jsonb_set(v_collected, array[v_resource], to_jsonb(coalesce((v_collected->>v_resource)::numeric, 0) + v_pending), true);
      v_company := jsonb_set(v_company, '{occupationTaxPending}', to_jsonb(0), true);
    end if;

    v_companies := v_companies || jsonb_build_array(v_company);
  end loop;

  if v_collected = '{}'::jsonb then
    raise exception 'No hay tasas pendientes en ese territorio.';
  end if;

  select string_agg(format('%s %s', value, key), ', ' order by key)
  into v_collected_text
  from jsonb_each_text(v_collected);

  v_save := jsonb_set(v_save, '{companies}', v_companies, true);
  v_save := jsonb_set(v_save, '{inventory}', v_inventory, true);

  insert into public.astracorp_territory_events(user_id, territory_id, action, payload)
  values (auth.uid(), p_territory_id, 'collect_tax', jsonb_build_object('collected', v_collected));

  perform public._astracorp_store_save(v_save);
  return jsonb_build_object('ok', true, 'saveData', v_save, 'collectedText', v_collected_text, 'message', 'Tasas cobradas online.');
end;
$fn$
language plpgsql
security definer
set search_path = public;

grant execute on function public.rpc_get_global_territories() to authenticated;
grant execute on function public.rpc_attack_territory_secure(integer) to authenticated;
grant execute on function public.rpc_reinforce_territory_secure(integer) to authenticated;
grant execute on function public.rpc_sabotage_territory_secure(integer) to authenticated;
grant execute on function public.rpc_build_territory_fort_secure(integer) to authenticated;
grant execute on function public.rpc_collect_occupation_taxes_secure(integer) to authenticated;
