-- AstraCorp - mercado global multijugador online
-- Ejecutar en Supabase SQL Editor.

create table if not exists public.game_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.game_saves enable row level security;

drop policy if exists "Players can read own save" on public.game_saves;
create policy "Players can read own save"
  on public.game_saves for select
  using (auth.uid() = user_id);

drop policy if exists "Players can write own save" on public.game_saves;
create policy "Players can write own save"
  on public.game_saves for insert
  with check (auth.uid() = user_id);

drop policy if exists "Players can update own save" on public.game_saves;
create policy "Players can update own save"
  on public.game_saves for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.astracorp_global_market (
  item_key text primary key,
  state jsonb not null,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.astracorp_global_market enable row level security;

drop policy if exists "Players can read global market" on public.astracorp_global_market;
create policy "Players can read global market"
  on public.astracorp_global_market for select
  to authenticated
  using (true);

create table if not exists public.astracorp_market_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_key text not null,
  action text not null,
  qty numeric not null default 0,
  unit_price numeric not null default 0,
  total numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists astracorp_market_events_user_idx
  on public.astracorp_market_events(user_id, created_at desc);

alter table public.astracorp_market_events enable row level security;

drop policy if exists "Players can read own market events" on public.astracorp_market_events;
create policy "Players can read own market events"
  on public.astracorp_market_events for select
  using (auth.uid() = user_id);

create or replace function public._astracorp_market_price(p_base numeric, p_demand numeric, p_supply numeric)
returns numeric
as $fn$
  select round((p_base * greatest(0.5, least(2.2, 0.8 + (p_demand / greatest(p_supply, 1)) * 0.45)))::numeric, 2);
$fn$
language sql
immutable;

create or replace function public._astracorp_market_trade_price(
  p_current numeric,
  p_base numeric,
  p_demand numeric,
  p_supply numeric,
  p_qty numeric,
  p_action text
)
returns numeric
as $fn$
  select round(
    greatest(
      greatest(0.01, p_base * 0.35),
      least(
        p_base * 2.8,
        p_current + case when p_action = 'buy' then 1 else -1 end * (p_qty * 0.01)
      )
    )::numeric,
    2
  );
$fn$
language sql
immutable;

create or replace function public._astracorp_market_load_save_locked()
returns jsonb
as $fn$
declare
  v_user uuid := auth.uid();
  v_save jsonb;
begin
  if v_user is null then
    raise exception 'Debes iniciar sesion.';
  end if;

  v_save := (
    select save_data
    from public.game_saves
    where user_id = v_user
    for update
  );

  if v_save is null then
    raise exception 'No hay partida guardada en esta cuenta.';
  end if;

  insert into public.astracorp_global_market(item_key, state, updated_by, updated_at)
  select item.key, item.value, v_user, now()
  from jsonb_each(coalesce(v_save->'market', '{}'::jsonb)) item
  on conflict (item_key) do nothing;

  v_save := jsonb_set(
    v_save,
    '{market}',
    (
      select coalesce(jsonb_object_agg(item.key, coalesce(global_item.state, item.value)), '{}'::jsonb)
      from jsonb_each(coalesce(v_save->'market', '{}'::jsonb)) item
      left join public.astracorp_global_market global_item on global_item.item_key = item.key
    ),
    true
  );

  return v_save;
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_market_store_save(p_save jsonb)
returns void
as $fn$
begin
  update public.game_saves
  set save_data = p_save,
      updated_at = now()
  where user_id = auth.uid();
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_market_write_item(p_item_key text, p_state jsonb)
returns void
as $fn$
begin
  insert into public.astracorp_global_market(item_key, state, updated_by, updated_at)
  values (p_item_key, p_state, auth.uid(), now())
  on conflict (item_key) do update set
    state = excluded.state,
    updated_by = excluded.updated_by,
    updated_at = now();
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_get_global_market()
returns jsonb
as $fn$
declare
  v_save jsonb;
begin
  v_save := public._astracorp_market_load_save_locked();
  perform public._astracorp_market_store_save(v_save);

  return jsonb_build_object(
    'ok', true,
    'market', coalesce(v_save->'market', '{}'::jsonb),
    'saveData', v_save
  );
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_buy_market_item_secure(p_item_key text, p_qty integer)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_item jsonb;
  v_next_item jsonb;
  v_qty integer;
  v_supply numeric;
  v_demand numeric;
  v_base numeric;
  v_price numeric;
  v_total numeric;
  v_credits numeric;
  v_energy numeric;
  v_inventory jsonb;
  v_stats jsonb;
  v_basis jsonb;
  v_basis_item jsonb;
  v_basis_qty numeric;
  v_basis_value numeric;
  v_next_price numeric;
  v_global_buys numeric;
  v_global_sells numeric;
  v_net_flow numeric;
begin
  v_qty := greatest(1, least(250, coalesce(p_qty, 1)));
  v_save := public._astracorp_market_load_save_locked();
  v_item := v_save #> array['market', p_item_key];

  if v_item is null then raise exception 'Ese recurso no existe en el mercado.'; end if;

  v_supply := greatest(0, coalesce((v_item->>'supply')::numeric, 0));
  if v_supply <= 0 then raise exception 'Sin stock disponible ahora mismo.'; end if;

  v_qty := least(v_qty, floor(v_supply)::int);
  v_price := coalesce((v_item->>'price')::numeric, 0);
  v_credits := coalesce((v_save #>> '{player,credits}')::numeric, 0);
  v_energy := coalesce((v_save #>> '{player,energy}')::numeric, 0);

  if v_energy < 1 then raise exception 'Necesitas 1 de energia.'; end if;

  v_base := coalesce((v_item->>'base')::numeric, v_price);
  v_next_price := public._astracorp_market_trade_price(v_price, v_base, coalesce((v_item->>'demand')::numeric, 1), v_supply, v_qty, 'buy');
  v_total := round((v_next_price * 1.08 * v_qty)::numeric, 2);

  if v_credits < v_total then raise exception 'Creditos insuficientes.'; end if;

  v_global_buys := coalesce((v_item->>'globalBuys')::numeric, 0) + v_qty;
  v_global_sells := coalesce((v_item->>'globalSells')::numeric, 0);
  v_net_flow := v_global_buys - v_global_sells;

  v_demand := coalesce((v_item->>'demand')::numeric, 0) + 2.8 * v_qty;
  v_supply := greatest(0, v_supply - v_qty);
  v_next_item := jsonb_set(v_item, '{demand}', to_jsonb(v_demand), true);
  v_next_item := jsonb_set(v_next_item, '{supply}', to_jsonb(v_supply), true);
  v_next_item := jsonb_set(v_next_item, '{price}', to_jsonb(v_next_price), true);
  v_next_item := jsonb_set(v_next_item, '{lastTradeAt}', to_jsonb((extract(epoch from now()) * 1000)::bigint), true);
  v_next_item := jsonb_set(v_next_item, '{lastTradeAction}', to_jsonb('buy'::text), true);
  v_next_item := jsonb_set(v_next_item, '{lastTradeQty}', to_jsonb(v_qty), true);
  v_next_item := jsonb_set(v_next_item, '{lastPriceChange}', to_jsonb(round((v_next_price - v_price)::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{globalBuys}', to_jsonb(round(v_global_buys::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{globalSells}', to_jsonb(round(v_global_sells::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{netFlow}', to_jsonb(round(v_net_flow::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{marketPressure}', to_jsonb((case when v_net_flow > 0 then 'buy' when v_net_flow < 0 then 'sell' else 'flat' end)::text), true);

  v_inventory := coalesce(v_save->'inventory', '{}'::jsonb);
  v_inventory := jsonb_set(v_inventory, array[p_item_key], to_jsonb(round((coalesce((v_inventory->>p_item_key)::numeric, 0) + v_qty)::numeric, 2)), true);

  v_basis := coalesce(v_save->'marketCostBasis', '{}'::jsonb);
  v_basis_item := coalesce(v_basis->p_item_key, '{}'::jsonb);
  v_basis_qty := coalesce((v_basis_item->>'qty')::numeric, 0) + v_qty;
  v_basis_value := coalesce((v_basis_item->>'value')::numeric, 0) + v_total;
  v_basis_item := jsonb_build_object('qty', round(v_basis_qty::numeric, 2), 'value', round(v_basis_value::numeric, 2));
  v_basis := jsonb_set(v_basis, array[p_item_key], v_basis_item, true);

  v_stats := coalesce(v_save->'stats', '{}'::jsonb);
  v_stats := jsonb_set(v_stats, '{buys}', to_jsonb(coalesce((v_stats->>'buys')::int, 0) + v_qty), true);

  v_save := jsonb_set(v_save, array['market', p_item_key], v_next_item, true);
  v_save := jsonb_set(v_save, '{inventory}', v_inventory, true);
  v_save := jsonb_set(v_save, '{marketCostBasis}', v_basis, true);
  v_save := jsonb_set(v_save, '{stats}', v_stats, true);
  v_save := jsonb_set(v_save, '{player,credits}', to_jsonb(round((v_credits - v_total)::numeric, 2)), true);
  v_save := jsonb_set(v_save, '{player,energy}', to_jsonb(greatest(0, floor(v_energy - 1))::int), true);

  perform public._astracorp_market_write_item(p_item_key, v_next_item);
  insert into public.astracorp_market_events(user_id, item_key, action, qty, unit_price, total)
  values (auth.uid(), p_item_key, 'buy', v_qty, case when v_qty > 0 then round((v_total / v_qty)::numeric, 2) else 0 end, v_total);
  perform public._astracorp_market_store_save(v_save);

  return jsonb_build_object('ok', true, 'saveData', v_save, 'qty', v_qty, 'totalCost', v_total, 'message', format('Comprado x%s por %s creditos.', v_qty, v_total));
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_sell_market_item_secure(p_item_key text, p_qty integer)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_item jsonb;
  v_next_item jsonb;
  v_qty integer;
  v_owned numeric;
  v_supply numeric;
  v_demand numeric;
  v_base numeric;
  v_post_price numeric;
  v_market_unit numeric;
  v_total numeric;
  v_credits numeric;
  v_energy numeric;
  v_inventory jsonb;
  v_basis jsonb;
  v_basis_item jsonb;
  v_basis_qty numeric;
  v_basis_value numeric;
  v_bought_sell_qty numeric;
  v_produced_sell_qty numeric;
  v_avg_cost numeric;
  v_capped_bought_unit numeric;
  v_next_price numeric;
  v_global_buys numeric;
  v_global_sells numeric;
  v_net_flow numeric;
begin
  v_qty := greatest(1, least(250, coalesce(p_qty, 1)));
  v_save := public._astracorp_market_load_save_locked();
  v_item := v_save #> array['market', p_item_key];

  if v_item is null then raise exception 'Ese recurso no existe en el mercado.'; end if;

  v_inventory := coalesce(v_save->'inventory', '{}'::jsonb);
  v_owned := coalesce((v_inventory->>p_item_key)::numeric, 0);
  if v_owned <= 0 then raise exception 'No tienes ese recurso.'; end if;

  v_qty := least(v_qty, floor(v_owned)::int);
  v_energy := coalesce((v_save #>> '{player,energy}')::numeric, 0);
  if v_energy < 1 then raise exception 'Necesitas 1 de energia.'; end if;

  v_base := coalesce((v_item->>'base')::numeric, coalesce((v_item->>'price')::numeric, 1));
  v_post_price := coalesce((v_item->>'price')::numeric, v_base);
  v_next_price := public._astracorp_market_trade_price(v_post_price, v_base, coalesce((v_item->>'demand')::numeric, 1), coalesce((v_item->>'supply')::numeric, 1), v_qty, 'sell');
  v_market_unit := round((v_post_price * 0.78)::numeric, 2);

  v_supply := coalesce((v_item->>'supply')::numeric, 0) + v_qty;
  v_demand := greatest(0, coalesce((v_item->>'demand')::numeric, 0) - v_qty * 2.4);
  v_global_buys := coalesce((v_item->>'globalBuys')::numeric, 0);
  v_global_sells := coalesce((v_item->>'globalSells')::numeric, 0) + v_qty;
  v_net_flow := v_global_buys - v_global_sells;

  v_basis := coalesce(v_save->'marketCostBasis', '{}'::jsonb);
  v_basis_item := coalesce(v_basis->p_item_key, '{}'::jsonb);
  v_basis_qty := greatest(0, coalesce((v_basis_item->>'qty')::numeric, 0));
  v_basis_value := greatest(0, coalesce((v_basis_item->>'value')::numeric, 0));
  v_bought_sell_qty := least(v_qty, v_basis_qty);
  v_produced_sell_qty := greatest(0, v_qty - v_bought_sell_qty);
  v_avg_cost := case when v_basis_qty > 0 then v_basis_value / v_basis_qty else v_market_unit end;
  v_capped_bought_unit := least(v_market_unit, v_avg_cost * 0.72);
  v_total := round((v_bought_sell_qty * v_capped_bought_unit + v_produced_sell_qty * v_market_unit)::numeric, 2);

  v_basis_qty := round(greatest(0, v_basis_qty - v_bought_sell_qty)::numeric, 2);
  v_basis_value := round(greatest(0, v_basis_value - v_avg_cost * v_bought_sell_qty)::numeric, 2);
  v_basis := jsonb_set(v_basis, array[p_item_key], jsonb_build_object('qty', v_basis_qty, 'value', v_basis_value), true);

  v_next_item := jsonb_set(v_item, '{demand}', to_jsonb(v_demand), true);
  v_next_item := jsonb_set(v_next_item, '{supply}', to_jsonb(v_supply), true);
  v_next_item := jsonb_set(v_next_item, '{price}', to_jsonb(v_next_price), true);
  v_next_item := jsonb_set(v_next_item, '{lastTradeAt}', to_jsonb((extract(epoch from now()) * 1000)::bigint), true);
  v_next_item := jsonb_set(v_next_item, '{lastTradeAction}', to_jsonb('sell'::text), true);
  v_next_item := jsonb_set(v_next_item, '{lastTradeQty}', to_jsonb(v_qty), true);
  v_next_item := jsonb_set(v_next_item, '{lastPriceChange}', to_jsonb(round((v_next_price - v_post_price)::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{globalBuys}', to_jsonb(round(v_global_buys::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{globalSells}', to_jsonb(round(v_global_sells::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{netFlow}', to_jsonb(round(v_net_flow::numeric, 2)), true);
  v_next_item := jsonb_set(v_next_item, '{marketPressure}', to_jsonb((case when v_net_flow > 0 then 'buy' when v_net_flow < 0 then 'sell' else 'flat' end)::text), true);

  v_inventory := jsonb_set(v_inventory, array[p_item_key], to_jsonb(round(greatest(0, v_owned - v_qty)::numeric, 2)), true);
  v_credits := coalesce((v_save #>> '{player,credits}')::numeric, 0);

  v_save := jsonb_set(v_save, array['market', p_item_key], v_next_item, true);
  v_save := jsonb_set(v_save, '{inventory}', v_inventory, true);
  v_save := jsonb_set(v_save, '{marketCostBasis}', v_basis, true);
  v_save := jsonb_set(v_save, '{player,credits}', to_jsonb(round((v_credits + v_total)::numeric, 2)), true);
  v_save := jsonb_set(v_save, '{player,energy}', to_jsonb(greatest(0, floor(v_energy - 1))::int), true);

  perform public._astracorp_market_write_item(p_item_key, v_next_item);
  insert into public.astracorp_market_events(user_id, item_key, action, qty, unit_price, total)
  values (auth.uid(), p_item_key, 'sell', v_qty, case when v_qty > 0 then round((v_total / v_qty)::numeric, 2) else 0 end, v_total);
  perform public._astracorp_market_store_save(v_save);

  return jsonb_build_object('ok', true, 'saveData', v_save, 'qty', v_qty, 'totalReceived', v_total, 'message', format('+%s creditos', v_total));
end;
$fn$
language plpgsql
security definer
set search_path = public;

grant execute on function public.rpc_get_global_market() to authenticated;
grant execute on function public.rpc_buy_market_item_secure(text, integer) to authenticated;
grant execute on function public.rpc_sell_market_item_secure(text, integer) to authenticated;

