-- AstraCorp - empresas online server-first
-- Ejecutar por bloques en Supabase SQL Editor si el editor corta funciones largas.

create table if not exists public.game_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.game_saves enable row level security;

drop policy if exists "Players can read own save" on public.game_saves;
create policy "Players can read own save"
  on public.game_saves for select
  using (auth.uid() = user_id);

drop policy if exists "Players can write own save" on public.game_saves;
create policy "Players can write own save"
  on public.game_saves for insert
  with check (auth.uid() = user_id);

drop policy if exists "Players can update own save" on public.game_saves;
create policy "Players can update own save"
  on public.game_saves for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.astracorp_company_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  company_id text,
  company_type text,
  resource_key text,
  amount numeric not null default 0,
  credits numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists astracorp_company_events_user_idx
  on public.astracorp_company_events(user_id, created_at desc);

alter table public.astracorp_company_events enable row level security;

drop policy if exists "Players can read own company events" on public.astracorp_company_events;
create policy "Players can read own company events"
  on public.astracorp_company_events for select
  using (auth.uid() = user_id);

create or replace function public._astracorp_company_meta(p_type text)
returns jsonb
as $fn$
begin
  return case p_type
    when 'dew_collector' then jsonb_build_object('key','dew_collector','name','Captador de rocio','buildCost',12,'resourceKey','water','resourceLabel','Agua','ratePerHour',12,'maxStorage',64,'unlockLevel',1,'inputs','[]'::jsonb)
    when 'solar_panel' then jsonb_build_object('key','solar_panel','name','Panel solar','buildCost',22,'resourceKey','energy_cells','resourceLabel','Energia','ratePerHour',9.5,'maxStorage',56,'unlockLevel',2,'inputs','[]'::jsonb)
    when 'surface_mine' then jsonb_build_object('key','surface_mine','name','Mina de superficie','buildCost',34,'resourceKey','mineral','resourceLabel','Mineral','ratePerHour',7.2,'maxStorage',46,'unlockLevel',3,'inputs','[]'::jsonb)
    when 'water_purifier' then jsonb_build_object('key','water_purifier','name','Planta de purificacion','buildCost',64,'resourceKey','purified_water','resourceLabel','Agua purificada','ratePerHour',5.8,'maxStorage',40,'unlockLevel',4,'inputs',jsonb_build_array(jsonb_build_object('key','water','amount',2),jsonb_build_object('key','energy_cells','amount',1)))
    when 'smelter' then jsonb_build_object('key','smelter','name','Fundicion','buildCost',84,'resourceKey','metal_components','resourceLabel','Componentes metalicos','ratePerHour',4.8,'maxStorage',36,'unlockLevel',5,'inputs',jsonb_build_array(jsonb_build_object('key','mineral','amount',2),jsonb_build_object('key','energy_cells','amount',1)))
    when 'electrolysis_plant' then jsonb_build_object('key','electrolysis_plant','name','Planta de electrolisis','buildCost',164,'resourceKey','oxygen_tanks','resourceLabel','Tanques de oxigeno','ratePerHour',2.8,'maxStorage',24,'unlockLevel',6,'inputs',jsonb_build_array(jsonb_build_object('key','purified_water','amount',2),jsonb_build_object('key','energy_cells','amount',2)))
    when 'industrial_forge' then jsonb_build_object('key','industrial_forge','name','Forja industrial','buildCost',196,'resourceKey','alloy_frames','resourceLabel','Estructuras de aleacion','ratePerHour',2.4,'maxStorage',22,'unlockLevel',7,'inputs',jsonb_build_array(jsonb_build_object('key','metal_components','amount',2),jsonb_build_object('key','mineral','amount',1),jsonb_build_object('key','energy_cells','amount',2)))
    when 'habitat_factory' then jsonb_build_object('key','habitat_factory','name','Fabrica de habitats','buildCost',276,'resourceKey','habitat_modules','resourceLabel','Modulos de habitat','ratePerHour',1.4,'maxStorage',14,'unlockLevel',9,'inputs',jsonb_build_array(jsonb_build_object('key','oxygen_tanks','amount',1),jsonb_build_object('key','alloy_frames','amount',1),jsonb_build_object('key','purified_water','amount',1)))
    when 'research_lab' then jsonb_build_object('key','research_lab','name','Laboratorio orbital','buildCost',228,'resourceKey','research_support','resourceLabel','Soporte cientifico','ratePerHour',0,'maxStorage',0,'unlockLevel',8,'inputs','[]'::jsonb)
    else null
  end;
end;
$fn$
language plpgsql
immutable;

create or replace function public._astracorp_company_build_cost(p_type text, p_owned integer)
returns numeric
as $fn$
declare
  v_meta jsonb := public._astracorp_company_meta(p_type);
  v_base numeric;
begin
  if v_meta is null then return 0; end if;
  v_base := coalesce((v_meta->>'buildCost')::numeric, 0);
  return greatest(v_base, round((v_base * power(1.18, greatest(0, coalesce(p_owned, 0))))::numeric, 0));
end;
$fn$
language plpgsql
immutable;

create or replace function public._astracorp_company_load_save_locked()
returns jsonb
as $fn$
declare
  v_user uuid := auth.uid();
  v_save jsonb;
begin
  if v_user is null then
    raise exception 'Debes iniciar sesion.';
  end if;

  v_save := (
    select save_data
    from public.game_saves
    where user_id = v_user
    for update
  );

  if v_save is null then
    raise exception 'No hay partida guardada en esta cuenta.';
  end if;

  return v_save;
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_company_store_save(p_save jsonb)
returns void
as $fn$
begin
  update public.game_saves
  set save_data = p_save,
      updated_at = now()
  where user_id = auth.uid();
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_company_spend_energy(p_save jsonb, p_amount numeric)
returns jsonb
as $fn$
declare
  v_energy numeric := coalesce((p_save #>> '{player,energy}')::numeric, 0);
begin
  if v_energy < p_amount then
    raise exception 'Necesitas % de energia.', p_amount;
  end if;

  return jsonb_set(p_save, '{player,energy}', to_jsonb(greatest(0, floor(v_energy - p_amount))::int), true);
end;
$fn$
language plpgsql
immutable;

create or replace function public._astracorp_company_hydrate(p_save jsonb)
returns jsonb
as $fn$
declare
  v_now_ms numeric := extract(epoch from clock_timestamp()) * 1000;
  v_inventory jsonb := coalesce(p_save->'inventory', '{}'::jsonb);
  v_companies jsonb := '[]'::jsonb;
  v_company jsonb;
  v_meta jsonb;
  v_type text;
  v_rate numeric;
  v_max numeric;
  v_storage numeric;
  v_last numeric;
  v_elapsed_hours numeric;
  v_produced numeric;
  v_input jsonb;
  v_input_key text;
  v_input_amount numeric;
  v_max_by_inputs numeric;
  v_available numeric;
begin
  for v_company in select value from jsonb_array_elements(coalesce(p_save->'companies', '[]'::jsonb)) loop
    if coalesce((v_company->>'active')::boolean, true) = false then
      v_companies := v_companies || jsonb_build_array(v_company);
      continue;
    end if;

    v_type := coalesce(v_company->>'companyType', v_company->>'type');
    v_meta := public._astracorp_company_meta(v_type);
    if v_meta is null then
      v_companies := v_companies || jsonb_build_array(v_company);
      continue;
    end if;

    v_rate := coalesce((v_company->>'effectiveRatePerHour')::numeric, (v_meta->>'ratePerHour')::numeric, 0);
    v_max := coalesce((v_company->>'maxStorage')::numeric, (v_meta->>'maxStorage')::numeric, 0);
    v_storage := least(v_max, greatest(0, coalesce((v_company->>'storage')::numeric, 0)));
    v_last := coalesce((v_company->>'lastTickAt')::numeric, (v_company->>'lastCollectedAt')::numeric, (v_company->>'createdAt')::numeric, v_now_ms);
    v_elapsed_hours := greatest(0, v_now_ms - v_last) / 3600000.0;
    v_produced := least(greatest(0, v_max - v_storage), greatest(0, v_elapsed_hours * v_rate));

    if jsonb_array_length(coalesce(v_meta->'inputs', '[]'::jsonb)) > 0 and v_produced > 0 then
      v_max_by_inputs := v_produced;
      for v_input in select value from jsonb_array_elements(v_meta->'inputs') loop
        v_input_key := v_input->>'key';
        v_input_amount := coalesce((v_input->>'amount')::numeric, 0);
        if v_input_amount > 0 then
          v_available := coalesce((v_inventory->>v_input_key)::numeric, 0);
          v_max_by_inputs := least(v_max_by_inputs, v_available / v_input_amount);
        end if;
      end loop;
      v_produced := greatest(0, v_max_by_inputs);

      if v_produced > 0 then
        for v_input in select value from jsonb_array_elements(v_meta->'inputs') loop
          v_input_key := v_input->>'key';
          v_input_amount := coalesce((v_input->>'amount')::numeric, 0);
          if v_input_amount > 0 then
            v_inventory := jsonb_set(v_inventory, array[v_input_key], to_jsonb(round(greatest(0, coalesce((v_inventory->>v_input_key)::numeric, 0) - v_input_amount * v_produced)::numeric, 2)), true);
          end if;
        end loop;
      end if;
    end if;

    v_company := jsonb_set(v_company, '{storage}', to_jsonb(round(least(v_max, v_storage + v_produced)::numeric, 2)), true);
    v_company := jsonb_set(v_company, '{lastTickAt}', to_jsonb(floor(v_now_ms)::bigint), true);
    v_company := jsonb_set(v_company, '{companyType}', to_jsonb(v_type), true);
    v_company := jsonb_set(v_company, '{type}', to_jsonb(v_type), true);
    v_company := jsonb_set(v_company, '{name}', to_jsonb(coalesce(v_company->>'name', v_meta->>'name')), true);
    v_company := jsonb_set(v_company, '{maxStorage}', to_jsonb(v_max), true);

    v_companies := v_companies || jsonb_build_array(v_company);
  end loop;

  p_save := jsonb_set(p_save, '{inventory}', v_inventory, true);
  p_save := jsonb_set(p_save, '{companies}', v_companies, true);
  return p_save;
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_build_company_secure(p_company_type_key text, p_region_key text default null, p_territory_id integer default null)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_meta jsonb;
  v_type text := p_company_type_key;
  v_owned integer;
  v_cost numeric;
  v_credits numeric;
  v_level numeric;
  v_now_ms bigint := floor(extract(epoch from clock_timestamp()) * 1000)::bigint;
  v_company jsonb;
  v_stats jsonb;
begin
  v_meta := public._astracorp_company_meta(v_type);
  if v_meta is null then raise exception 'Tipo de empresa no valido.'; end if;

  v_save := public._astracorp_company_load_save_locked();
  v_save := public._astracorp_company_hydrate(v_save);
  v_level := coalesce((v_save #>> '{player,level}')::numeric, 1);
  if v_level < coalesce((v_meta->>'unlockLevel')::numeric, 1) then
    raise exception 'Necesitas nivel % para construir esta empresa.', v_meta->>'unlockLevel';
  end if;

  v_owned := (
    select count(*)::int
    from jsonb_array_elements(coalesce(v_save->'companies', '[]'::jsonb)) c
    where coalesce(c->>'companyType', c->>'type') = v_type
  );
  v_cost := public._astracorp_company_build_cost(v_type, v_owned);
  v_credits := coalesce((v_save #>> '{player,credits}')::numeric, 0);
  if v_credits < v_cost then raise exception 'Creditos insuficientes.'; end if;

  v_save := public._astracorp_company_spend_energy(v_save, 4);
  v_save := jsonb_set(v_save, '{player,credits}', to_jsonb(round((v_credits - v_cost)::numeric, 2)), true);

  v_company := jsonb_build_object(
    'id', v_now_ms::text || '-' || substr(md5(random()::text), 1, 8),
    'companyType', v_type,
    'type', v_type,
    'name', v_meta->>'name',
    'storage', 0,
    'maxStorage', coalesce((v_meta->>'maxStorage')::numeric, 0),
    'regionKey', coalesce(p_region_key, v_save #>> '{player,currentRegion}', 'alpha-district'),
    'territoryId', p_territory_id,
    'active', true,
    'status', 'active',
    'occupiedBy', null,
    'occupationTaxPending', 0,
    'occupationTaxResourceKey', v_meta->>'resourceKey',
    'ownerName', coalesce(v_save #>> '{player,name}', 'Jugador'),
    'createdAt', v_now_ms,
    'lastCollectedAt', v_now_ms,
    'lastTickAt', v_now_ms
  );

  v_save := jsonb_set(v_save, '{companies}', coalesce(v_save->'companies', '[]'::jsonb) || jsonb_build_array(v_company), true);
  v_stats := coalesce(v_save->'stats', '{}'::jsonb);
  v_stats := jsonb_set(v_stats, '{companiesBuilt}', to_jsonb(coalesce((v_stats->>'companiesBuilt')::int, 0) + 1), true);
  v_save := jsonb_set(v_save, '{stats}', v_stats, true);

  insert into public.astracorp_company_events(user_id, action, company_id, company_type, credits)
  values (auth.uid(), 'build', v_company->>'id', v_type, v_cost);

  perform public._astracorp_company_store_save(v_save);
  return jsonb_build_object('ok', true, 'saveData', v_save, 'company', v_company, 'cost', v_cost);
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_sell_company_secure(p_company_id text)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_company jsonb;
  v_companies jsonb := '[]'::jsonb;
  v_type text;
  v_owned integer;
  v_refund numeric;
  v_credits numeric;
begin
  if p_company_id is null then raise exception 'Empresa no valida.'; end if;

  v_save := public._astracorp_company_load_save_locked();
  v_save := public._astracorp_company_hydrate(v_save);

  v_company := (
    select value
    from jsonb_array_elements(coalesce(v_save->'companies', '[]'::jsonb))
    where value->>'id' = p_company_id
    limit 1
  );

  if v_company is null then raise exception 'La empresa ya no existe.'; end if;
  v_type := coalesce(v_company->>'companyType', v_company->>'type');
  if public._astracorp_company_meta(v_type) is null then raise exception 'Tipo de empresa no valido.'; end if;

  v_owned := (
    select count(*)::int
    from jsonb_array_elements(coalesce(v_save->'companies', '[]'::jsonb)) c
    where coalesce(c->>'companyType', c->>'type') = v_type
  );
  v_refund := round(greatest(1, public._astracorp_company_build_cost(v_type, greatest(0, v_owned - 1)) * 0.45)::numeric, 2);

  v_companies := (
    select coalesce(jsonb_agg(value), '[]'::jsonb)
    from jsonb_array_elements(coalesce(v_save->'companies', '[]'::jsonb))
    where value->>'id' <> p_company_id
  );

  v_credits := coalesce((v_save #>> '{player,credits}')::numeric, 0);
  v_save := jsonb_set(v_save, '{companies}', v_companies, true);
  v_save := jsonb_set(v_save, '{player,credits}', to_jsonb(round((v_credits + v_refund)::numeric, 2)), true);

  insert into public.astracorp_company_events(user_id, action, company_id, company_type, credits)
  values (auth.uid(), 'sell', p_company_id, v_type, v_refund);

  perform public._astracorp_company_store_save(v_save);
  return jsonb_build_object('ok', true, 'saveData', v_save, 'refund', v_refund);
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public._astracorp_collect_companies(p_company_id text default null, p_company_type_key text default null, p_region_key text default null, p_spend_energy numeric default 1)
returns jsonb
as $fn$
declare
  v_save jsonb;
  v_companies jsonb := '[]'::jsonb;
  v_inventory jsonb;
  v_company jsonb;
  v_meta jsonb;
  v_type text;
  v_resource_key text;
  v_resource_label text;
  v_storage numeric;
  v_total numeric := 0;
  v_totals jsonb := '{}'::jsonb;
  v_match boolean;
  v_summary text;
begin
  v_save := public._astracorp_company_load_save_locked();
  v_save := public._astracorp_company_hydrate(v_save);
  if p_spend_energy > 0 then
    v_save := public._astracorp_company_spend_energy(v_save, p_spend_energy);
  end if;
  v_inventory := coalesce(v_save->'inventory', '{}'::jsonb);

  for v_company in select value from jsonb_array_elements(coalesce(v_save->'companies', '[]'::jsonb)) loop
    v_type := coalesce(v_company->>'companyType', v_company->>'type');
    v_meta := public._astracorp_company_meta(v_type);
    v_storage := coalesce((v_company->>'storage')::numeric, 0);
    v_match := true;
    if p_company_id is not null then v_match := v_company->>'id' = p_company_id; end if;
    if p_company_type_key is not null then v_match := v_match and v_type = p_company_type_key; end if;
    if p_region_key is not null then v_match := v_match and coalesce(v_company->>'regionKey', 'alpha-district') = p_region_key; end if;

    if v_match and v_meta is not null and v_storage > 0 and coalesce((v_meta->>'ratePerHour')::numeric, 0) > 0 then
      v_resource_key := v_meta->>'resourceKey';
      v_resource_label := v_meta->>'resourceLabel';
      v_inventory := jsonb_set(v_inventory, array[v_resource_key], to_jsonb(round((coalesce((v_inventory->>v_resource_key)::numeric, 0) + v_storage)::numeric, 2)), true);
      v_totals := jsonb_set(v_totals, array[v_resource_key], to_jsonb(round((coalesce((v_totals->>v_resource_key)::numeric, 0) + v_storage)::numeric, 2)), true);
      v_total := round((v_total + v_storage)::numeric, 2);
      v_company := jsonb_set(v_company, '{storage}', to_jsonb(0), true);
      v_company := jsonb_set(v_company, '{lastCollectedAt}', to_jsonb(floor(extract(epoch from clock_timestamp()) * 1000)::bigint), true);
      v_company := jsonb_set(v_company, '{lastTickAt}', to_jsonb(floor(extract(epoch from clock_timestamp()) * 1000)::bigint), true);
    end if;

    v_companies := v_companies || jsonb_build_array(v_company);
  end loop;

  if v_total <= 0 then
    raise exception 'No hay produccion acumulada.';
  end if;

  v_summary := (
    select string_agg(format('%s %s', value, key), ', ' order by key)
    from jsonb_each_text(v_totals)
  );

  v_save := jsonb_set(v_save, '{inventory}', v_inventory, true);
  v_save := jsonb_set(v_save, '{companies}', v_companies, true);

  insert into public.astracorp_company_events(user_id, action, company_id, company_type, resource_key, amount)
  values (auth.uid(), case when p_company_id is not null then 'collect_one' when p_company_type_key is not null then 'collect_group' else 'collect_all_ad' end, p_company_id, p_company_type_key, null, v_total);

  perform public._astracorp_company_store_save(v_save);
  return jsonb_build_object('ok', true, 'saveData', v_save, 'amount', v_total, 'resourceLabel', coalesce(v_resource_label, ''), 'totals', v_totals, 'summary', coalesce(v_summary, 'Produccion recogida'));
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_collect_company_secure(p_company_id text)
returns jsonb
as $fn$
begin
  if p_company_id is null then raise exception 'Empresa no valida.'; end if;
  return public._astracorp_collect_companies(p_company_id, null, null, 1);
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_collect_company_group_secure(p_company_type_key text, p_region_key text default null)
returns jsonb
as $fn$
begin
  if p_company_type_key is null then raise exception 'Tipo de empresa no valido.'; end if;
  return public._astracorp_collect_companies(null, p_company_type_key, p_region_key, 1);
end;
$fn$
language plpgsql
security definer
set search_path = public;

create or replace function public.rpc_collect_all_companies_ad_secure()
returns jsonb
as $fn$
begin
  return public._astracorp_collect_companies(null, null, null, 0);
end;
$fn$
language plpgsql
security definer
set search_path = public;

grant execute on function public.rpc_build_company_secure(text, text, integer) to authenticated;
grant execute on function public.rpc_sell_company_secure(text) to authenticated;
grant execute on function public.rpc_collect_company_secure(text) to authenticated;
grant execute on function public.rpc_collect_company_group_secure(text, text) to authenticated;
grant execute on function public.rpc_collect_all_companies_ad_secure() to authenticated;

